version: 2.1
orbs:
  node: circleci/node@4.1.0
executors:
  default:
    working_directory: ~/mattermost-redux
    docker:
      - image: circleci/node:11.3.0

aliases:
  - &restore_cache
    restore_cache:
      key: dependencies-{{ checksum "package-lock.json" }}
  - &save_cache
    save_cache:
      key: dependencies-{{ checksum "package-lock.json" }}
      paths:
        - node_modules

jobs:
  install:
    executor:
      name: default
    steps:
      - checkout
      - run: ls -la
      - *restore_cache
      - run: npm ci
      - run: ls -la
      - *save_cache

  lint:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: npm run check
      - run: npm run tsc

  test:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: npm test
      - store_artifacts:
          path: build
      - store_test_results:
          path: build

workflows:
  version: 2
  pr-build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - lint
